name: Sync Wiki

on:
  push:
    paths:
      - '**/*.md'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório principal
      uses: actions/checkout@v3

    - name: Clonar o repositório Wiki
      run: |
        git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

    - name: Copiar arquivos .md modificados/novos para a Wiki
      run: |
        # Encontra todos os arquivos .md no repositório principal (exceto na pasta wiki) e copia para a Wiki
        find . -name "*.md" -not -path "./wiki/*" -exec cp --parents -u {} wiki/ \;

    - name: Commit e Push das alterações na Wiki
      run: |
        cd wiki
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        # Verifica se há alterações antes de fazer commit
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "Sincronizando modificações dos arquivos .md na Wiki"
          git push
        else
          echo "Nenhuma modificação detectada, nada a commitar."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
