name: Sync Wiki

on:
  push:
    paths:
      - '**/*.md'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório principal
      uses: actions/checkout@v3

    - name: Clonar o repositório Wiki
      run: |
        git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git wiki

    - name: Copiar todos os arquivos .md para a Wiki
      run: |
        # Cria a estrutura de pastas na Wiki, se necessário
        mkdir -p wiki
        # Copia todos os arquivos .md, preservando a estrutura de diretórios
        find . -name "*.md" -not -path "./wiki/*" -exec cp --parents {} wiki/ \;

    - name: Commit e Push das alterações na Wiki
      run: |
        cd wiki
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Atualizando Wiki com base nos arquivos .md do repositório"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
